name: infotech

services:
  php:
    image: yiisoftware/yii2-php:8.2-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - "8040:80"
    networks:
      - it-network

  database:
    image: mariadb
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: it
    volumes:
      - database_data:/var/lib/mysql
      - ./docker/dumps:/dumps
    working_dir: /dumps
    ports:
      - "3300:3306"
    networks:
      - it-network

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
    networks:
      - it-network

networks:
  it-network:

volumes:
  database_data:
